(()=>{
const c=supabase.createClient(VOLTTECH_SUPABASE.url,VOLTTECH_SUPABASE.publishableKey),root=document.querySelector("#document"),x=v=>String(v??"").replace(/[&<>\"]/g,a=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[a])),m=n=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(Number(n||0)),d=v=>v?new Intl.DateTimeFormat("en-ZA",{dateStyle:"long"}).format(new Date(v)):"—",cap=v=>v?String(v).charAt(0).toUpperCase()+String(v).slice(1):"";
const loginUrl=()=>`account.html?returnTo=${encodeURIComponent(location.pathname+location.search+location.hash)}`;
const payableStatuses=new Set(["issued","sent","due","overdue","unpaid","partially_paid","partial","open","pending","payment_due"]);
async function pay(id,button,message){button.disabled=true;button.textContent="Opening secure checkout…";message.textContent="";try{const{data,error}=await c.functions.invoke("create-yoco-checkout",{body:{invoice_id:id}});if(error)throw error;if(!data?.redirect_url)throw new Error("No checkout URL returned");location.href=data.redirect_url}catch(e){console.error(e);message.textContent="Test checkout could not be started. Please try again.";button.disabled=false;button.textContent="Pay securely — TEST"}}
async function load(){
 const{data:{session}}=await c.auth.getSession();if(!session){location.replace(loginUrl());return}
 const id=new URLSearchParams(location.search).get("id");if(!id){root.innerHTML="<p>Invoice not specified.</p>";return}
 const{data:i,error}=await c.from("invoices").select("id,invoice_number,status,currency,subtotal,delivery_fee,discount_total,tax_total,total,vat_registered,customer_name,customer_email,customer_company,customer_suburb,issued_at,due_at,paid_at,quote_id,invoice_items(position,item_type,description,quantity,unit_price,line_total)").eq("id",id).maybeSingle();if(error||!i){root.innerHTML="<p>Invoice could not be loaded.</p>";return}
 const email=document.querySelector("#emailCopy");email.hidden=false;email.dataset.emailKind="invoice";email.dataset.emailId=id;const state=String(i.status||"").toLowerCase(),paid=state==="paid",canPay=payableStatuses.has(state);
 const paymentBlock=paid?`<div style="margin-top:20px"><a class="btn" href="receipt.html?id=${encodeURIComponent(i.id)}">Open payment receipt</a></div>`:canPay?`<div style="margin-top:22px"><button id="testPay" class="btn" type="button">Pay securely — TEST</button><p id="payMessage" class="small" aria-live="polite"></p><p class="small">Test mode only. No real payment will be taken.</p></div>`:`<div style="margin-top:22px"><p class="small">Online checkout is not available for this invoice status.</p></div>`;
 root.innerHTML=`<article class="sheet"><div class="top"><div class="brand"><div class="brandline"><img src="logo-badge.png" alt=""><h1>VoltTech Computer Co.</h1></div><p>PC & technology services · Pretoria, Gauteng<br>volttechcomputerco@gmail.com · +27 61 843 5775</p></div><div class="doc"><h2>Invoice</h2><div class="num">${x(i.invoice_number)}</div><p class="meta">${x(cap(i.status))}</p></div></div><div class="grid"><div class="block"><strong>Billed to</strong><p>${x(i.customer_name||"Customer")}${i.customer_company?`<br>${x(i.customer_company)}`:""}${i.customer_email?`<br>${x(i.customer_email)}`:""}${i.customer_suburb?`<br>${x(i.customer_suburb)}`:""}</p></div><div class="block"><strong>Invoice details</strong><p>Issued: ${d(i.issued_at)}${i.due_at?`<br>Due: ${d(i.due_at)}`:""}${i.paid_at?`<br>Paid: ${d(i.paid_at)}`:""}</p></div></div><table class="items"><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>${[...(i.invoice_items||[])].sort((a,b)=>a.position-b.position).map(v=>`<tr><td>${x(v.description)}</td><td>${v.quantity}</td><td>${m(v.unit_price)}</td><td>${m(v.line_total)}</td></tr>`).join("")}</tbody></table><div class="totals"><div class="row"><span>Subtotal</span><b>${m(i.subtotal)}</b></div>${i.delivery_fee?`<div class="row"><span>Delivery</span><b>${m(i.delivery_fee)}</b></div>`:""}${i.discount_total?`<div class="row"><span>Discount</span><b>− ${m(i.discount_total)}</b></div>`:""}${i.tax_total?`<div class="row"><span>Tax</span><b>${m(i.tax_total)}</b></div>`:""}<div class="row grand"><span>Total</span><b>${m(i.total)}</b></div></div>${paymentBlock}<div class="notice">${i.vat_registered?"Tax treatment is shown above.":"VoltTech is not presenting this document as a VAT tax invoice."} This invoice does not replace statutory consumer rights. ${paid?"Payment has been recorded.":canPay?"Online payment remains in test mode.":"Payment availability follows the invoice's current status."}</div></article>`;
 if(canPay){const b=document.querySelector("#testPay"),msg=document.querySelector("#payMessage");b.addEventListener("click",()=>pay(i.id,b,msg))}
}
load()
})();
