import {STAGES,nextAction,normalize} from './operations-model.js?v=20261007-customer-workflow';
const c=supabase.createClient(VOLTTECH_SUPABASE.url,VOLTTECH_SUPABASE.publishableKey),q=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]));
const money=n=>n==null?'Unconfirmed':new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(Number(n));
const stamp=v=>v?new Date(v).toLocaleString('en-ZA'):'Not recorded';
const icons={done:'✅',action:'⚡',waiting:'⏳',problem:'⚠',blocked:'🚫'};
const tabs=['Inbox / Needs action','Orders','Quotes','Suppliers','Delivery','Payments','Customers','Catalogue','Completed'];
let data={},customers=[],offers=[],jobs=[],selected=new URLSearchParams(location.search).get('job'),tab=new URLSearchParams(location.search).get('section')||'Inbox / Needs action',busy=false;
const input=(id,label,value='',type='text')=>`<label>${esc(label)}<input id="${esc(id)}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01"':''}></label>`;
function active(){return jobs.find(j=>j.key===selected)}
let quoteSource=null;
async function load(){
 q('#opsStatus').textContent='Loading verified operations…';q('#opsRefresh').disabled=true;
 try{const user=await c.auth.getUser();if(!user.data.user)return;
 const adm=await c.rpc('is_volttech_admin');if(adm.error||adm.data!==true)throw new Error('Admin access required');
 const [dr,cr,sr]=await Promise.all([c.rpc('admin_operations_data'),c.rpc('admin_customers'),c.from('store_supplier_offers').select('*').order('supplier_name').limit(1000)]);
 for(const r of [dr,cr,sr])if(r.error)throw r.error;
 data=dr.data;customers=cr.data||[];offers=sr.data||[];jobs=normalize(data,customers);render();q('#opsStatus').textContent=`${jobs.length} jobs · last refreshed ${stamp(new Date())}`;
 }catch(e){q('#opsStatus').textContent='⚠ '+e.message;q('#opsStatus').className='ops-error';}finally{q('#opsRefresh').disabled=false;}
}
function matches(j){const n=nextAction(j),closed=!!j.ops.archived_at;
 if(tab==='Completed')return closed;if(closed)return false;
 if(tab==='Inbox / Needs action')return n.tone==='action'||n.tone==='problem';
 if(tab==='Orders')return j.kind==='store'||j.kind==='order';
 if(tab==='Quotes')return j.kind==='quote'||['price','send_quote','release_payment','revise'].includes(n.action)||n.stage===3;
 if(tab==='Delivery')return j.paid&&!closed;
 if(tab==='Payments')return n.stage===4||j.paid;
 return true;
}
function render(){
 q('#opsTabs').innerHTML=tabs.map(t=>`<button type="button" data-tab="${esc(t)}" aria-selected="${t===tab}">${esc(t)}</button>`).join('');
 q('#opsTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
 const tool=['Catalogue','Suppliers','Customers'].includes(tab);q('#opsTool').hidden=!tool;q('#opsLayout').hidden=tool;
 if(tool){renderTool();return;}
 const term=q('#opsSearch').value.trim().toLowerCase(),rows=jobs.filter(matches).filter(j=>[j.ref,j.customer,j.email,j.title,...j.items.map(i=>i.product_name||i.description)].join(' ').toLowerCase().includes(term));
 q('#opsList').innerHTML=rows.map(j=>{const n=nextAction(j);return `<button class="ops-card ${j.key===selected?'selected':''}" data-job="${esc(j.key)}"><small>${esc(j.ref)} · ${esc(j.kind)}</small><strong>${esc(j.customer)}</strong><span>${icons[n.tone]} ${esc(n.label)}</span><small>${money(j.total)} · ${stamp(j.date)}</small></button>`}).join('')||'<p class="muted">No jobs in this view. Use Orders or Quotes to see waiting work.</p>';
 q('#opsList').querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>{selected=b.dataset.job;history.replaceState(null,'','?job='+encodeURIComponent(selected));render()});
 workspace();
}
function renderTool(){const el=q('#opsTool');
 if(tab==='Catalogue'){el.innerHTML='<div class="ops-panel"><h2>Catalogue management</h2><iframe class="ops-embed" title="Catalogue editor" src="admin-store.html?embedded=catalogue"></iframe></div>';return;}
 if(tab==='Suppliers'){el.innerHTML=`<div class="ops-panel"><h2>Supplier desk</h2><p>Esquire · Account <strong>VLHR01</strong> · Brenton John · <a href="mailto:brenton@esquire.co.za">brenton@esquire.co.za</a></p><p>71 Landmarks Ave, Samrand Business Park, Centurion, 0157</p><p class="ops-notice">Feed availability is NOT reserved stock. Supplier invoices and supplier prices must never be included with the customer parcel.</p><label>Search supplier / SKU / product<input id="offerSearch" type="search"></label><div id="offerRows"></div></div>`;
 const show=()=>{const term=q('#offerSearch').value.toLowerCase();q('#offerRows').innerHTML=offers.filter(o=>[o.supplier_name,o.supplier_sku,o.product_id].join(' ').toLowerCase().includes(term)).slice(0,60).map(o=>`<div class="ops-line"><strong>${esc(o.supplier_name)} · ${esc(o.supplier_sku)}</strong><p>Feed: ${esc(o.stock_status)} · Qty ${esc(o.stock_qty)} · Cost ${money(o.cost_price)} · checked ${stamp(o.last_checked)}</p></div>`).join('')||'<p>No matching supplier offers. Syntech and Tarsus can be selected manually on reservation lines when confirmed.</p>'};q('#offerSearch').oninput=show;show();return;}
 el.innerHTML=`<div class="ops-panel"><h2>Customer history</h2><label>Find customer<input id="opsCustomerSearch" type="search"></label><div id="opsCustomerRows"></div><div id="opsCustomerHistory"></div></div>`;
 const show=()=>{const term=q('#opsCustomerSearch').value.toLowerCase();q('#opsCustomerRows').innerHTML=customers.filter(c=>[c.full_name,c.billing_email,c.phone].join(' ').toLowerCase().includes(term)).map(c=>`<button class="ops-card" data-customer="${esc(c.id)}"><strong>${esc(c.full_name||c.billing_email)}</strong><small>${esc(c.billing_email)} · ${esc(c.phone)}</small></button>`).join('');q('#opsCustomerRows').querySelectorAll('button').forEach(b=>b.onclick=()=>{q('#opsCustomerHistory').innerHTML=jobs.filter(j=>j.user_id===b.dataset.customer).map(j=>`<button class="ops-card" data-history-job="${esc(j.key)}">${esc(j.ref)} · ${icons[nextAction(j).tone]} ${esc(nextAction(j).label)}</button>`).join('')+`<iframe class="ops-embed" title="Customer history, builds and documents" src="admin-customer.html?id=${encodeURIComponent(b.dataset.customer)}"></iframe>`;q('#opsCustomerHistory').querySelectorAll('[data-history-job]').forEach(x=>x.onclick=()=>{selected=x.dataset.historyJob;tab='Orders';render()})})};q('#opsCustomerSearch').oninput=show;show();
}
function productLines(j){return j.kind==='store'?j.items:j.items.filter(i=>['part','product'].includes(i.item_type))}
function workspace(){const j=active();if(!j){q('#opsWorkspace').innerHTML='<div class="ops-panel">Select a job to open its complete workflow.</div>';return;}const o=j.ops,r=j.record,n=nextAction(j);
 const customerEmails=(data.emails||[]).filter(e=>(e.source_id===j.key||e.source_id===r.id||e.source_id===j.invoice?.id)&&['operations_customer','quote_ready','invoice_issued'].includes(e.message_kind));const lastCustomer=customerEmails[0];
 const supplierCost=(o.reservations||[]).reduce((sum,x)=>sum+Number(x.cost||0)*Number(x.reserved_quantity||0),0),margin=j.total==null?null:Number(j.total)-supplierCost-Number(o.courier_cost??r.final_delivery_fee??r.delivery_fee??0);
 q('#opsWorkspace').innerHTML=`<div class="ops-panel"><div class="ops-top"><div><span class="ops-kicker">${esc(j.ref)} / ${esc(j.kind)}</span><h2>${esc(j.customer)}</h2><p>${esc(j.email)} · ${esc(j.phone)}</p><small>Source: ${esc(r.source||r.source_type||j.kind)} · ${stamp(j.date)}</small></div><strong>${money(j.total)}</strong></div>
 <div class="ops-next"><span class="ops-kicker">NEXT ACTION ${icons[n.tone]}</span><h2>${esc(n.label)}</h2>${n.action?`<button class="primary" id="opsNext">${esc(n.action.replaceAll('_',' ').toUpperCase())} →</button>`:'<p>Waiting on the customer or payment provider. Refresh to check the latest state.</p>'}</div>
 <div class="ops-timeline" aria-label="Workflow progress">${STAGES.map((s,i)=>`<div class="ops-step ${i===n.stage?'current':''}"><span>${i<n.stage?'✅':i===n.stage?icons[n.tone]:'🚫'}</span>${s}</div>`).join('')}</div>
 <div class="ops-summary"><div><small>Supplier cost confirmed</small><strong>${o.stock_confirmed_at?money(supplierCost):'Pending'}</strong></div><div><small>Gross contribution before labour / overhead</small><strong>${o.stock_confirmed_at?money(margin):'Pending'}</strong></div><div><small>Courier cost</small><strong>${money(o.courier_cost)}</strong></div><div><small>Payment</small><strong>${j.paid?'✅ Verified paid':esc(r.payment_status||j.invoice?.status||'Not released')}</strong></div></div>
 <section class="ops-panel"><p class="ops-kicker">LATEST CUSTOMER UPDATE</p><p>${lastCustomer?esc(lastCustomer.payload?.message||lastCustomer.subject):'No recent customer update recorded.'}</p>${lastCustomer?`<small>Email: ${esc(lastCustomer.status)} · ${stamp(lastCustomer.created_at)}</small>`:''}${o.customer_link?`<p><a class="btn" href="${esc(o.customer_link)}" target="_blank" rel="noreferrer">Open latest customer quote / payment / tracking →</a></p>`:''}</section>
 <div id="opsActionPanel"></div>
 <details open><summary>Customer items and quote</summary><p>Labour ${money(o.quote_details?.labour??0)}</p>${j.items.map(i=>`<div class="ops-line"><strong>${esc(i.product_name||i.description)}</strong> · Qty ${esc(i.quantity)} · ${money(i.displayed_price??i.unit_price)}</div>`).join('')}<p>Delivery ${money(r.final_delivery_fee??r.delivery_fee)} · Discount ${money(r.discount_total??o.quote_details?.discount??0)} · VAT ${money(r.tax_total??0)} ${r.vat_registered?'':'(no separate VAT charged)'}</p><p>${esc(r.customer_note)}</p></details>
 <details><summary>What the customer sees</summary><div class="ops-preview"><h3>${esc(j.ref)}</h3><p>${o.stock_confirmed_at?'✅':'⏳'} Stock confirmed</p><p>${o.pricing_confirmed_at?'✅':'⏳'} Quote confirmed · ${money(j.total)}</p><p>${j.paid?'✅':'⏳'} Payment received</p><p>${o.supplier_order_at?'✅':'⏳'} Preparing order</p><p>${o.courier_booked_at?'✅':'🚫'} Courier booked</p><p>${o.in_transit_at?'✅':'🚫'} In transit</p><p>${o.delivered_at?'✅':'🚫'} Delivered</p></div></details>
 <details><summary>Supplier and courier instructions</summary><p>Esquire account VLHR01 · Brenton John · brenton@esquire.co.za</p><p>Direct collection: 71 Landmarks Ave, Samrand Business Park, Centurion, 0157.</p><p>Confirm order after payment. Book Bob Go manually, attach the downloaded waybill to the supplier email, then mark sent. No supplier invoice or pricing in the customer parcel.</p><p>SO: ${esc(o.supplier_order_reference||'Not recorded')} · Tracking: ${esc(r.tracking_number||o.shipment?.tracking||'Not recorded')}</p><p>Reservation: ${esc((o.reservations||[]).map(x=>[x.supplier,x.sku,x.reference].join(' / ')).join('; '))}</p></details>
 <details><summary>Full history and email delivery</summary><div class="ops-history">${(o.history||[]).map(h=>`<p>${stamp(h.at)} · ${esc(h.action.replaceAll('_',' '))}</p>`).join('')||'<p>No operational actions recorded.</p>'}${(data.emails||[]).filter(e=>e.source_id===j.key||e.source_id===r.id||e.source_id===j.invoice?.id).map(e=>`<p>${esc(e.subject)} · ${esc(e.status)} ${e.error_message?'⚠ '+esc(e.error_message):''}</p>`).join('')}</div></details>
 <div class="ops-actions">${j.kind==='quote'?`<a class="btn" href="quote.html?id=${encodeURIComponent(r.id)}" target="_blank">Preview customer quote</a>`:''}${o.final_invoice&&o.customer_link?`<a class="btn" href="${esc(o.customer_link)}" target="_blank" rel="noreferrer">Final customer invoice</a>`:''}${j.invoice?`<a class="btn" href="invoice.html?id=${encodeURIComponent(j.invoice.id)}" target="_blank">Final invoice</a>`:''}${o.quote_sent_at&&!o.payment_released_at&&!j.paid?'<button id="opsRevise">Revise quotation</button>':''}<button id="opsPreview">Preview customer view</button></div></div>`;
 q('#opsNext')?.addEventListener('click',()=>actionForm(j,n.action));q('#opsRevise')?.addEventListener('click',()=>perform(j,'revise',{}));q('#opsPreview').onclick=()=>{const details=q('.ops-preview').parentElement;details.open=true;details.scrollIntoView({behavior:'smooth'})};
}
function actionForm(j,action){const el=q('#opsActionPanel'),o=j.ops,r=j.record;
 if(action==='new_quote'){openQuote(j.user_id,j);return;}
 if(action==='build_quote'){perform(j,action,{});return;}
 let fields='';
 if(action==='reserve'){fields='<p class="ops-notice">Feed stock is informational. Record actual reserved quantity and SO reference, or physically held local stock. Confirm cost on the same VAT basis as selling price.</p>'+productLines(j).map(i=>{const saved=(o.reservations||[]).find(x=>x.item_id===i.id)||{},offer=offers.find(x=>x.product_id===i.product_id)||{};return `<div class="ops-line" data-reserve-line="${esc(i.id)}"><strong>${esc(i.product_name||i.description)} · Required ${esc(i.quantity)}</strong><small>Feed: ${esc(offer.stock_status||'Unavailable')} · Qty ${esc(offer.stock_qty??'unknown')} · ${stamp(offer.last_checked)}</small><div class="ops-grid"><label>Reservation state<select data-field="state"><option value="">Choose evidence</option><option value="reserved">Reserved with supplier</option><option value="local">Physically held locally</option></select></label>${field('supplier','Supplier',saved.supplier||offer.supplier_name||i.supplier||'')}${field('sku','Supplier SKU',saved.sku||offer.supplier_sku||i.supplier_sku||'')}${field('reference','SO / reservation reference',saved.reference||'')}${field('reserved_quantity','Reserved quantity',saved.reserved_quantity??i.quantity,'number')}${field('cost','Confirmed unit cost incl. VAT',saved.cost??offer.cost_price??i.supplier_cost??'','number')}</div></div>`}).join('');if(!productLines(j).length)fields='<p>No product lines. Confirm this is a service-only quotation requiring no supplier stock.</p>';}
 if(action==='price'){fields=(j.kind==='store'&&!j.paid)?j.items.map(i=>`<div class="ops-line" data-price-line="${esc(i.id)}"><strong>${esc(i.product_name)} · Qty ${esc(i.quantity)}</strong>${field('unit_price','Selling unit price incl. VAT',i.displayed_price??'','number')}</div>`).join('')+input('opsLabour','Labour',o.quote_details?.labour??0,'number')+input('opsDiscount','Discount',o.quote_details?.discount??0,'number')+input('opsDelivery','Confirmed manual delivery charge',r.final_delivery_fee??r.delivery_fee_estimate??0,'number'):j.kind==='quote'&&r.status==='draft'?j.items.map(i=>`<div class="ops-line" data-price-line="${esc(i.id)}"><strong>${esc(i.description)} · Qty ${esc(i.quantity)}</strong>${field('unit_price','Selling unit price',i.unit_price??'','number')}</div>`).join('')+input('opsDiscount','Discount',r.discount_total??0,'number')+input('opsDelivery','Delivery',r.delivery_fee??0,'number'):`<p>Confirm the existing quote pricing: labour, delivery, discount, VAT and total ${money(r.total)}. Preview the document before proceeding.</p>`;}
 if(action==='supplier_order')fields=input('opsReference','Confirmed supplier SO / order reference');
 if(action==='courier')fields='<p>Book Bob Go manually using the confirmed collection and customer delivery details.</p><p>'+esc(Object.values(r.shipping_address||{}).filter(v=>typeof v==='string').join(', '))+'</p>'+input('opsTracking','Bob Go shipment / tracking reference')+input('opsWaybill','Waybill reference')+input('opsTrackingURL','HTTPS tracking URL','','url')+input('opsCourierCost','Actual courier cost',r.final_delivery_fee??0,'number');
 if(action==='waybill_approved')fields='<p>Record this only after the supplier has confirmed the waybill and collection arrangements. This opens customer tracking.</p>';
 if(action==='waybill_sent'){const subject='VoltTech VLHR01 — waybill '+j.ref,body='Hi Brenton,\nPlease prepare the reserved order '+(o.supplier_order_reference||'')+' for courier collection.\nBob Go shipment: '+(r.tracking_number||'')+'\nThe waybill PDF is attached. Please exclude supplier invoices and pricing from the customer parcel.\nThank you, VoltTech Computer Co.';fields=`<p>Download the PDF from your Bob Go booking. Attach it to the email before sending.</p><a class="btn" href="mailto:brenton@esquire.co.za?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}">Prepare email to Brenton ↗</a><p>Only record this after you have sent the email with its attachment.</p>`;}
 el.innerHTML=`<form id="opsActionForm" class="ops-panel"><h3>${esc(action.replaceAll('_',' '))}</h3>${fields}<p id="opsActionError" class="ops-error" role="alert"></p><div class="ops-actions"><button type="submit" class="primary">${action==='waybill_sent'?'Confirm waybill emailed':'Confirm '+esc(action.replaceAll('_',' '))}</button><button type="button" id="opsCancel">Cancel</button></div></form>`;
 q('#opsCancel').onclick=()=>el.replaceChildren();q('#opsActionForm').onsubmit=e=>{e.preventDefault();let payload={};if(action==='reserve')payload.reservations=[...el.querySelectorAll('[data-reserve-line]')].map(row=>({item_id:row.dataset.reserveLine,...Object.fromEntries([...row.querySelectorAll('[data-field]')].map(x=>[x.dataset.field,x.type==='number'?Number(x.value):x.value]))}));if(action==='price'&&((j.kind==='store'&&!j.paid)||(j.kind==='quote'&&r.status==='draft')))payload={delivery:Number(q('#opsDelivery').value),labour:Number(q('#opsLabour')?.value||0),discount:Number(q('#opsDiscount').value),pricing:[...el.querySelectorAll('[data-price-line]')].map(row=>({item_id:row.dataset.priceLine,unit_price:Number(row.querySelector('input').value)}))};if(action==='supplier_order')payload.reference=q('#opsReference').value;if(action==='courier')payload={tracking:q('#opsTracking').value,waybill:q('#opsWaybill').value,url:q('#opsTrackingURL').value,cost:Number(q('#opsCourierCost').value)};perform(j,action,payload)};el.scrollIntoView({behavior:'smooth',block:'center'});
}
function field(name,label,value='',type='text'){return `<label>${esc(label)}<input data-field="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01"':''}></label>`}
async function perform(j,action,payload){if(busy)return;busy=true;q('#opsActionForm button[type=submit]')?.setAttribute('disabled','');try{let result;if(action==='build_quote')result=await c.rpc('admin_quote_saved_build',{p_build_id:j.record.id});else result=await c.rpc('admin_operations_action',{p_key:j.key,p_action:action,p_data:payload});if(result.error)throw result.error;await load();if(result.data?.new_key){selected=result.data.new_key;tab='Quotes';render();}if(result.data?.private_link){q('#opsActionPanel').innerHTML=`<div class="ops-notice">Customer update queued. <a href="${esc(result.data.private_link)}" target="_blank" rel="noreferrer">Open private customer link ↗</a></div>`;}q('#opsStatus').textContent='✅ '+action.replaceAll('_',' ')+' recorded';}catch(e){const el=q('#opsActionError')||q('#opsStatus');el.textContent='⚠ '+e.message;}finally{busy=false;q('#opsActionForm button[type=submit]')?.removeAttribute('disabled');}}
function openQuote(uid,source){quoteSource=source||null;q('#opsTool').hidden=true;q('#opsLayout').hidden=false;const panel=q('#quoteForm').parentElement;panel.hidden=false;if(uid){const cust=customers.find(x=>x.id===uid);q('#customer').value=uid;q('#selectedCustomer').textContent=cust?.full_name||cust?.billing_email||uid;}panel.scrollIntoView({behavior:'smooth'});}
q('#opsRefresh').onclick=load;q('#opsSearch').oninput=render;q('#opsNew').onclick=()=>openQuote();
for(const panel of document.querySelectorAll('#app > .panel'))panel.hidden=true;
document.addEventListener('volttech:quote-created',async e=>{if(quoteSource){const link=await c.rpc('admin_link_quote_source',{p_quote_id:e.detail.id,p_source_type:quoteSource.kind,p_source_id:quoteSource.record.id,p_metadata:{}});if(link.error){q('#opsStatus').textContent='Quote created; linking failed: '+link.error.message;return;}quoteSource=null;}selected='quote:'+e.detail.id;tab='Quotes';q('#quoteForm').parentElement.hidden=true;await load();});
load();

setInterval(()=>{if(!document.hidden&&!busy&&!q('#opsActionForm')&&q('#quoteForm').parentElement.hidden)load();},30000);
