import './common.js';
import {page,q,esc,href,download,status} from '../ui.js';
import * as signal from '../models/signal-scan-model.js';
import * as stream from '../models/stream-scan-model.js';
import {saveSignalResult} from '../models/signal-scan-handoff.js';
import {saveStreamResult} from '../models/stream-scan-handoff.js';
const streaming=page.data.kind==='stream',model=streaming?stream:signal,params=new URLSearchParams(location.search),source=signal.allowedSources.includes(params.get('source'))?params.get('source'):null;
let answers=streaming?stream.createStreamAnswers():signal.createAnswers(),step=0;const storage=streaming?'vt_stream_scan_answers_v2':'vt_signal_scan_answers_v2';
try{const cached=JSON.parse(sessionStorage.getItem(storage)||'null');if(cached?.answers&&cached.source===source)answers={...answers,...cached.answers};}catch{}
if(source&&params.get('issue'))signal.applyContext(answers,source,params.get('issue'));
const questions=()=>streaming?stream.streamQuestions(answers):signal.scanQuestions(answers,source);
q('[data-scan-source]').href=href(streaming?'streaming-setup-south-africa.html':source?signal.sourceInfo[source].page:'pc-repair-pretoria.html');
function persist(){try{sessionStorage.setItem(storage,JSON.stringify({answers,source}));}catch{}}
function render(){const rows=questions();q('[data-step-number]').textContent=String(step+1).padStart(2,'0');q('[data-step-progress]').textContent=`${Math.min(step+1,rows.length)} / ${rows.length} STEPS`;q('[data-scan-back]').disabled=step===0;
 if(step<rows.length){const row=rows[step];q('[data-scan-view]').innerHTML=`<h2 tabindex="-1">${esc(row.title)}</h2><div class="choice-matrix">${row.options.map(([value,label])=>`<button class="choice-option" data-answer="${esc(value)}" aria-pressed="${answers[row.key]===value}"><strong>${esc(label)}</strong><span>↗</span></button>`).join('')}</div>`;for(const b of document.querySelectorAll('[data-answer]'))b.onclick=()=>{answers[row.key]=b.dataset.answer;if(!streaming){if(row.key==='context')signal.applyContext(answers,source||signal.scanMode(answers),b.dataset.answer);if(row.key==='symptom')answers.context=null;}for(const later of questions().slice(step+1))answers[later.key]=null;step++;persist();render();q('[data-scan-view] h2')?.focus();};return;}
 const result=streaming?stream.recommendationFor(answers):signal.resultConfig(answers,source),summary=(streaming?stream.resultRows(answers):signal.resultRows(answers));const title=result[0],description=result[1],service=streaming?result[2]:result[3],estimate=streaming?result[3]:result[2];const text=['Hi VoltTech,',`${streaming?'Stream':'Signal'} Scan summary`,title,description,...summary.map(([key,value])=>`${key}: ${value}`),`Suggested service: ${service}`,`Indicative estimate: ${estimate}`,'Please confirm the assessment, pricing and next step.'].join('\n');const payload={answers,source,title,description,service,estimate,summary,text,at:new Date().toISOString()};(streaming?saveStreamResult:saveSignalResult)(payload);
 q('[data-scan-view]').innerHTML=`<p class="eyebrow">YOUR STARTING POINT</p><h2 tabindex="-1">${esc(title)}</h2><p>${esc(description)}</p><p class="notice">${esc(service)} / ${esc(estimate)}. Indicative only; VoltTech confirms scope and final pricing. This is guidance, not a confirmed diagnosis.</p><dl class="fact-list">${summary.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><div class="row"><a class="button" href="https://wa.me/27618435775?text=${encodeURIComponent(text)}">Share on WhatsApp ↗</a><a class="button secondary" href="mailto:volttechcomputerco@gmail.com?subject=${encodeURIComponent((streaming?'Stream':'Signal')+' Scan summary')}&body=${encodeURIComponent(text)}">Email summary</a><button class="button secondary" data-export-scan>Export summary</button></div>`;q('[data-export-scan]').onclick=()=>download('VoltTech-scan-summary.txt',text,'text/plain');}
q('[data-scan-back]').onclick=()=>{step=Math.max(0,step-1);render();};q('[data-scan-restart]').onclick=()=>{answers=streaming?stream.createStreamAnswers():signal.createAnswers();step=0;persist();render();};render();
