import './common.js';
import {page,q,esc,href,money,empty,download,action,check,safeURL,status} from '../ui.js';
import {isProduction,requireUser} from '../adapters/session.js';
import {loadDocument,customerQuoteAction,quoteExpired} from '../adapters/customer-documents.js';
const kind=page.data.kind,host=q('[data-document-view]');let record;
q('[data-print]').onclick=()=>window.print();q('[data-export-document]').onclick=()=>record?download(`volttech-${kind}-${record.id}.json`,record):status('[data-document-status]','Open an authorised record first.');
async function start(){
 if(!isProduction()){host.innerHTML=empty('Your record. Your access.','Sign in on the live VoltTech domain to view your authorised documents.','account.html','Customer workspace');return;}
 const ctx=await requireUser();if(!ctx)return;const id=new URLSearchParams(location.search).get('id');if(!id||!/^[a-zA-Z0-9-]{1,80}$/.test(id))throw Error('Choose a record from your Documents workspace.');
 const data=check(await loadDocument(ctx.client,ctx.user,kind,id));if(!data)throw Error('This record is unavailable or you do not have access.');record=data.record||data;
 if(kind==='quote'&&record.status==='draft')throw Error('This quote has not been issued.');
 if(kind==='receipt'&&record.status!=='paid')throw Error('A receipt becomes available after payment is confirmed.');
 const ref=record.quote_number||record.invoice_number||record.proforma_number||record.order_number||record.job_number||record.title||record.name||record.id;
 const items=record.quote_items||record.invoice_items||record.order_items||record.items||record.build_data?.items||[];
 const rows=Array.isArray(items)?items:[];
 host.innerHTML=`<section class="panel document-sheet"><p class="eyebrow">${esc(kind.toUpperCase())} / ${esc(record.status||'record')}</p><h2>${esc(ref)}</h2>${record.customer_name?`<p>${esc(record.customer_name)}</p>`:''}<p>${esc(record.customer_note||record.notes||'')}</p>${rows.length?`<div class="table-scroll"><table><thead><tr><th>Item</th><th>Quantity</th><th>Amount</th></tr></thead><tbody>${rows.sort((a,b)=>(a.position||0)-(b.position||0)).map(i=>`<tr><td>${esc(i.description||i.name||i.product_name||'Item')}</td><td>${esc(i.quantity||i.qty||1)}</td><td>${money(i.line_total??(i.unit_price==null?null:i.unit_price*(i.quantity||i.qty||1)))}</td></tr>`).join('')}</tbody></table></div>`:''}<dl class="record-details">${['subtotal','delivery_fee','discount_total','tax_total','total','estimated_total'].filter(k=>record[k]!=null).map(k=>`<div><dt>${esc(k.replaceAll('_',' '))}</dt><dd>${money(record[k])}</dd></div>`).join('')}${['created_at','issued_at','due_at','paid_at','valid_until'].filter(k=>record[k]).map(k=>`<div><dt>${esc(k.replaceAll('_',' '))}</dt><dd>${esc(record[k])}</dd></div>`).join('')}</dl>${record.vat_registered===false?'<p class="muted">VoltTech is not VAT registered.</p>':''}<div data-record-actions></div></section>`;
 const actions=q('[data-record-actions]');if(data.quoteNumber)actions.insertAdjacentHTML('beforebegin',`<p>Related quote: ${esc(data.quoteNumber)}</p>`);if(kind==='build'&&data.quote)actions.insertAdjacentHTML('beforebegin',`<a class="text-link" href="${href('quote.html?id='+encodeURIComponent(data.quote.id))}">${esc(data.quote.quote_number)} / ${esc(data.quote.status)} ↗</a>`);if(kind==='service')actions.insertAdjacentHTML('beforebegin',`<p>${esc(record.device_name||'')}</p><p>Quoted: ${money(record.amount_quoted)} / Paid: ${money(record.amount_paid)}</p>`);
 if(kind==='quote'&&['sent','viewed'].includes(record.status)&&!quoteExpired(record)){
  actions.innerHTML=`<label class="check-row"><input type="checkbox" data-quote-consent> I have read this quote and its <a href="${href('quote-terms.html')}">terms</a>.</label><div class="row"><button class="button" data-accept>Accept quote</button><button class="button secondary" data-decline>Decline quote</button></div>`;
  for(const [selector,value]of [['[data-accept]','accepted'],['[data-decline]','declined']])q(selector).onclick=()=>action(q(selector),async()=>{if(!q('[data-quote-consent]').checked)throw Error('Please acknowledge the quote terms.');if(!confirm(`${value==='accepted'?'Accept':'Decline'} this quote?`))return;check(await customerQuoteAction(ctx.client,id,value));await start();status('[data-document-status]',`Quote ${value}.`);},'[data-document-status]');
 }
 if(kind==='invoice'&&record.currency==='ZAR'&&['issued','sent','due','overdue','unpaid','partially_paid','partial','open','pending','payment_due'].includes(record.status)&&Number(record.total)>=2){
  actions.innerHTML='<button class="button" data-invoice-pay>Pay securely ↗</button>';q('[data-invoice-pay]').onclick=()=>action(q('[data-invoice-pay]'),async()=>{const result=check(await ctx.client.functions.invoke('create-yoco-checkout',{body:{invoice_id:id}}));const target=safeURL(result.redirect_url);if(!target||new URL(target).hostname!=='c.yoco.com'||new URL(target).protocol!=='https:'||(new URL(target).port&&new URL(target).port!=='443'))throw Error('The payment provider did not return a valid checkout. Please contact VoltTech.');location.assign(target);},'[data-document-status]');
 }
 const updates=record.service_job_updates;if(Array.isArray(updates)&&updates.length)host.insertAdjacentHTML('beforeend',`<section class="section"><h2>Service updates</h2>${updates.map(u=>`<article class="record-card"><p>${esc(u.created_at)}</p><h3>${esc(u.title||u.status||'Update')}</h3><p>${esc(u.message||u.note||u.description||'')}</p></article>`).join('')}</section>`);
}
start().catch(e=>{host.innerHTML=empty('Record unavailable',e.message,'documents.html','Back to documents');});
