(function(){
'use strict';
const VT=window.VoltTechStore,client=VT.getClient();
const el={auth:document.getElementById('adminAuth'),stats:document.getElementById('adminStats'),requests:document.getElementById('requestList'),catalogue:document.getElementById('catalogueList'),filter:document.getElementById('requestFilter'),requestsPanel:document.getElementById('requestsPanel'),cataloguePanel:document.getElementById('cataloguePanel')};
let requests=[],products=[],customers=new Map();init();
async function init(){bind();try{const user=(await client.auth.getUser()).data?.user;if(!user){location.href='account.html';return}const admin=await client.rpc('is_volttech_admin');if(admin.error||!admin.data){document.body.innerHTML='<main class="admin-store"><div class="wrap"><div class="empty-state"><strong>Admin access required</strong>This page is only available to VoltTech administrators.<div style="margin-top:14px"><a class="btn primary" href="account.html">Back to account</a></div></div></div></main>';return}el.auth.textContent=`ADMIN VERIFIED · ${user.email||'VoltTech'}`;await loadAll()}catch(error){console.error(error);el.auth.textContent='Admin connection error';VT.toast('Could not open the Parts Desk.','error')}}
function bind(){document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===b));const isReq=b.dataset.adminTab==='requests';el.requestsPanel.hidden=!isReq;el.cataloguePanel.hidden=isReq}));el.filter?.addEventListener('change',renderRequests)}
async function loadAll(){const [reqRes,prodRes,custRes]=await Promise.all([client.from('store_requests').select('*,store_request_items(*)').order('submitted_at',{ascending:false}),client.from('store_products').select('*').order('sort_priority',{ascending:false}).order('name'),client.rpc('admin_customers')]);if(reqRes.error)throw reqRes.error;if(prodRes.error)throw prodRes.error;if(custRes.error)throw custRes.error;requests=reqRes.data||[];products=prodRes.data||[];customers=new Map((custRes.data||[]).map(c=>[c.id,c]));renderStats();renderRequests();renderCatalogue()}
function renderStats(){const open=requests.filter(r=>['submitted','reviewing'].includes(r.status)).length,quoted=requests.filter(r=>r.status==='quoted').length,live=products.filter(p=>p.status==='active'&&p.visibility==='public').length;el.stats.innerHTML=`<div class="stat-card"><b>${open}</b><span>Open requests</span></div><div class="stat-card"><b>${quoted}</b><span>Quoted</span></div><div class="stat-card"><b>${live}</b><span>Live products</span></div><div class="stat-card"><b>Quote-first</b><span>Checkout mode</span></div>`}
function visibleRequests(){const f=el.filter.value;if(f==='all')return requests;if(f==='open')return requests.filter(r=>['submitted','reviewing'].includes(r.status));return requests.filter(r=>r.status===f)}
function renderRequests(){const rows=visibleRequests();if(!rows.length){el.requests.innerHTML='<div class="empty-state"><strong>No matching requests</strong>Nothing needs attention in this view.</div>';return}el.requests.innerHTML=rows.map(requestCard).join('');el.requests.querySelectorAll('[data-quote-request]').forEach(b=>b.addEventListener('click',()=>quoteRequest(b.dataset.quoteRequest,b)))}
function requestCard(r){const c=customers.get(r.user_id)||{},items=r.store_request_items||[],quoted=!!r.quote_id;const today=new Date();today.setDate(today.getDate()+7);const valid=today.toISOString().slice(0,10);return`<article class="request-card"><div class="request-top"><div><div class="kicker">${VT.esc(r.request_number)} · ${VT.esc(r.status)}</div><h3>${VT.esc(c.full_name||c.billing_email||'VoltTech customer')}</h3><div class="request-meta">${VT.esc(c.billing_email||'No billing email')} · ${VT.esc(c.phone||'No phone')} · ${new Date(r.submitted_at).toLocaleString('en-ZA')}</div></div>${r.quote_id?`<a class="btn small" href="quote.html?id=${encodeURIComponent(r.quote_id)}">Open quote →</a>`:''}</div>${r.customer_note?`<p style="color:#9ab0ac;font-size:11px">Customer note: ${VT.esc(r.customer_note)}</p>`:''}<div class="request-items">${items.map(i=>`<div class="request-item"><div><b>${VT.esc(i.product_name)}</b><small>${VT.esc(i.brand)} · Qty ${i.quantity}</small></div><label class="admin-label">Unit price (R)<input class="admin-input" type="number" min="0" step="0.01" data-price-item="${VT.esc(i.id)}" ${quoted?'disabled':''}></label><label class="admin-label">Stock<select class="admin-input" data-stock-item="${VT.esc(i.id)}" ${quoted?'disabled':''}><option value="confirmed">Confirmed</option><option value="limited">Limited</option><option value="backorder">Backorder</option><option value="unknown">Unknown</option></select></label></div>`).join('')}</div>${!quoted?`<div class="request-foot"><label class="admin-label">Internal note<input class="admin-input" data-note-for="${VT.esc(r.id)}" placeholder="Supplier / sourcing note"></label><label class="admin-label">Delivery (R)<input class="admin-input" type="number" min="0" step="0.01" value="0" data-delivery-for="${VT.esc(r.id)}"></label><label class="admin-label">Valid until<input class="admin-input" type="date" value="${valid}" data-valid-for="${VT.esc(r.id)}"></label><button class="btn primary small" type="button" data-quote-request="${VT.esc(r.id)}">Create formal quote</button></div>`:''}</article>`}
async function quoteRequest(id,button){const r=requests.find(x=>x.id===id);if(!r)return;const items=r.store_request_items||[],pricing=[];for(const i of items){const price=Number(document.querySelector(`[data-price-item="${CSS.escape(i.id)}"]`)?.value);if(!Number.isFinite(price)||price<0){VT.toast(`Enter a selling price for ${i.product_name}.`,'error');return}pricing.push({item_id:i.id,unit_price:price,stock_status:document.querySelector(`[data-stock-item="${CSS.escape(i.id)}"]`)?.value||'unknown'})}const valid=document.querySelector(`[data-valid-for="${CSS.escape(id)}"]`)?.value,delivery=Number(document.querySelector(`[data-delivery-for="${CSS.escape(id)}"]`)?.value||0),note=document.querySelector(`[data-note-for="${CSS.escape(id)}"]`)?.value||'';if(!valid){VT.toast('Choose a quote validity date.','error');return}const original=button.textContent;button.disabled=true;button.textContent='Creating…';try{const res=await client.rpc('admin_quote_store_request',{p_request_id:id,p_valid_until:valid,p_delivery_fee:delivery,p_discount_total:0,p_pricing:pricing,p_internal_note:note});if(res.error)throw res.error;VT.toast('Formal parts quote created.');location.href=`quote.html?id=${encodeURIComponent(res.data)}`}catch(error){console.error(error);VT.toast(error.message||'Could not create the quote.','error');button.disabled=false;button.textContent=original}}
function renderCatalogue(){if(!products.length){el.catalogue.innerHTML='<div class="empty-state"><strong>No catalogue rows</strong>The store catalogue is empty.</div>';return}el.catalogue.innerHTML=products.map(p=>`<div class="catalogue-row"><div><h3>${VT.esc(p.name)}</h3><small>${VT.esc(p.brand)} · ${VT.esc(VT.categoryLabel(p.type))} · ${VT.esc(p.sale_mode)}</small></div><label class="toggle"><input type="checkbox" data-publish="${VT.esc(p.id)}" ${p.visibility==='public'&&p.status==='active'?'checked':''}> Published</label><label class="toggle"><input type="checkbox" data-feature="${VT.esc(p.id)}" ${p.featured?'checked':''}> Featured</label></div>`).join('');el.catalogue.querySelectorAll('[data-publish]').forEach(i=>i.addEventListener('change',()=>updateProduct(i.dataset.publish,{visibility:i.checked?'public':'private',status:'active'},i)));el.catalogue.querySelectorAll('[data-feature]').forEach(i=>i.addEventListener('change',()=>updateProduct(i.dataset.feature,{featured:i.checked},i)))}
async function updateProduct(id,patch,input){input.disabled=true;try{const r=await client.from('store_products').update({...patch,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;VT.toast('Catalogue updated.');const p=products.find(x=>x.id===id);if(p)Object.assign(p,patch);renderStats()}catch(error){console.error(error);input.checked=!input.checked;VT.toast('Could not update the catalogue.','error')}finally{input.disabled=false}}
})();
