(function(){
'use strict';
const VT=window.VoltTechStore,host=document.getElementById('statusHost');
const q=new URLSearchParams(location.search),ref=q.get('ref')||'',token=q.get('token')||'';
let timer=null;
init();
async function init(){if(!ref||!token){renderError('This order link is incomplete.');return}await load();timer=setInterval(load,30000)}
function money(v){return v==null?'—':VT.formatPrice(v,'ZAR')}
function stageInfo(o){if(o.payment_status==='paid'&&['booked','in_transit','delivered'].includes(o.delivery_status))return{title:o.delivery_status==='delivered'?'Delivered':o.delivery_status==='in_transit'?'On the way':'Courier booked',copy:o.delivery_status==='delivered'?'Your order has been delivered.':'Your parcel has been handed into the delivery workflow.'};if(o.payment_status==='paid')return{title:'Payment received',copy:'Your payment is verified. VoltTech is preparing your hardware for courier collection.'};if(o.checkout_stage==='awaiting_payment')return{title:'Ready for payment',copy:'Stock, pricing and delivery have been confirmed. You can pay securely now.'};return{title:'Order received',copy:'VoltTech is confirming the exact hardware, live stock and delivery before asking you to pay.'}}
async function load(){try{const o=await VT.getOrderStatus(ref,token);render(o)}catch(e){console.error(e);renderError('We could not load this order right now.')}}
function render(o){const info=stageInfo(o),paymentFlag=q.get('payment');host.innerHTML=`<div class="status-card"><div class="status-top"><div><div class="kicker">PC Parts // ${VT.esc(o.request_number)}</div><h1>${VT.esc(info.title)}</h1><p>${VT.esc(info.copy)}</p></div><div class="status-pill">${VT.esc(String(o.payment_status||'unpaid').replaceAll('_',' '))}</div></div>${paymentFlag?`<div class="status-notice ${paymentFlag==='success'?'good':''}">${paymentFlag==='success'?'Payment submitted — verification normally takes a moment.':paymentFlag==='cancelled'?'Payment was cancelled. Your order is still safe.':'The payment did not complete. You can try again.'}</div>`:''}<div class="status-steps">${step('1','Order received',true)}${step('2','Stock + delivery confirmed',!!o.confirmed_at)}${step('3','Payment received',o.payment_status==='paid')}${step('4','Courier booked',['booked','in_transit','delivered'].includes(o.delivery_status))}${step('5','Delivered',o.delivery_status==='delivered')}</div>${o.can_pay?paymentPanel(o):summary(o)}${tracking(o)}</div>`;document.getElementById('payNow')?.addEventListener('click',pay)}
function step(n,label,done){return`<div class="status-step ${done?'done':''}"><span>${done?'✓':n}</span><b>${VT.esc(label)}</b></div>`}
function paymentPanel(o){return`<section class="status-panel"><div class="kicker">Confirmed total</div><div class="total-row"><span>Hardware</span><b>${money(o.subtotal)}</b></div><div class="total-row"><span>Delivery</span><b>${money(o.delivery_fee)}</b></div><div class="grand-row"><span>Total</span><strong>${money(o.total)}</strong></div>${o.shipping_service?`<p class="muted">${VT.esc(o.shipping_service)}${o.shipping_eta?' · '+VT.esc(o.shipping_eta):''}</p>`:''}<button class="btn primary pay-btn" id="payNow">Pay securely with Yoco</button><p class="safe-note">Payment is processed by Yoco. VoltTech never receives your card details.</p></section>`}
function summary(o){return`<section class="status-panel"><div class="kicker">Order summary</div><div class="total-row"><span>Confirmed total</span><b>${o.total!=null?money(o.total):'Being confirmed'}</b></div><div class="total-row"><span>Delivery</span><b>${o.delivery_fee!=null?money(o.delivery_fee):'Being confirmed'}</b></div><p class="muted">This page updates automatically. You can keep it open or bookmark it.</p></section>`}
function tracking(o){if(!o.tracking_number&&!o.tracking_url)return'';return`<section class="status-panel"><div class="kicker">Delivery tracking</div><h2>${VT.esc(o.courier_name||'Courier')}</h2>${o.tracking_number?`<p>Tracking: <strong>${VT.esc(o.tracking_number)}</strong></p>`:''}${o.tracking_url?`<a class="btn ghost" href="${VT.esc(o.tracking_url)}" target="_blank" rel="noopener">Track parcel ↗</a>`:''}</section>`}
async function pay(){const b=document.getElementById('payNow');if(!b)return;b.disabled=true;b.textContent='Opening Yoco…';try{const r=await VT.createStorePayment(ref,token);if(!r?.redirect_url)throw new Error('Payment link unavailable');location.href=r.redirect_url}catch(e){VT.toast(e.message||'Could not start payment.','error');b.disabled=false;b.textContent='Pay securely with Yoco'}}
function renderError(msg){host.innerHTML=`<div class="status-card"><div class="kicker">PC Parts // Order status</div><h1>Order unavailable</h1><p>${VT.esc(msg)}</p><a class="btn primary" href="store.html">Back to PC Parts</a></div>`}
})();