(function(){
'use strict';
const VT=window.VoltTechStore;
const el={announcement:document.getElementById('announcement'),search:document.getElementById('search'),sort:document.getElementById('sort'),categoryRail:document.getElementById('categoryRail'),brands:document.getElementById('brandFilters'),grid:document.getElementById('productGrid'),count:document.getElementById('resultCount'),cartButton:document.getElementById('cartButton'),mobileCart:document.getElementById('mobileCart'),cartCount:document.getElementById('cartCount'),mobileCartCount:document.getElementById('mobileCartCount'),drawer:document.getElementById('cartDrawer'),scrim:document.getElementById('scrim'),close:document.getElementById('cartClose'),cartItems:document.getElementById('cartItems'),note:document.getElementById('quoteNote'),submit:document.getElementById('submitQuote')};
let data={settings:null,categories:[],products:[]},state={category:'all',brands:new Set(),search:'',sort:'featured'},productMap=new Map();
init();
async function init(){bind();relabelCommerce();updateCartBadge();try{data=await VT.loadStore();productMap=new Map(data.products.map(p=>[p.id,p]));if(!data.settings?.catalogue_enabled)throw new Error('The PC parts catalogue is temporarily unavailable.');if(el.announcement)el.announcement.textContent=data.settings.banner_text||'VoltTech PC Parts — checkout first, then we confirm live stock and delivery before payment.';const q=new URLSearchParams(location.search);const cat=q.get('category');if(cat&&data.categories.some(c=>c.slug===cat))state.category=cat;renderCategories();renderBrands();renderProducts();await renderCart();if(q.get('cart')==='1')openCart();VT.analytics('view_item_list',{item_list_name:'VoltTech PC Parts',items:data.products.slice(0,20).map(p=>({item_id:p.id,item_name:p.name,item_brand:p.brand,item_category:p.type}))});}catch(error){console.error(error);if(el.grid)el.grid.innerHTML=`<div class="empty-state"><strong>Catalogue unavailable</strong>${VT.esc(error.message||'Please try again shortly.')}</div>`;if(el.count)el.count.textContent='Unavailable';}}
function relabelCommerce(){const h=el.drawer?.querySelector('.drawer-head h2');if(h)h.textContent='Cart';const k=el.drawer?.querySelector('.drawer-head .kicker');if(k)k.textContent='VoltTech checkout';if(el.submit)el.submit.textContent='Continue to checkout';const foot=el.drawer?.querySelector('.drawer-foot p');if(foot)foot.textContent='No payment is taken yet. VoltTech confirms live stock, final pricing and delivery before you pay.';const label=el.mobileCart?.querySelector('b');if(label)label.textContent='CART';if(el.note)el.note.placeholder='Optional: tell us anything important about the order.'}
function bind(){el.search?.addEventListener('input',()=>{state.search=el.search.value.trim().toLowerCase();renderProducts()});el.sort?.addEventListener('change',()=>{state.sort=el.sort.value;renderProducts()});el.cartButton?.addEventListener('click',openCart);el.mobileCart?.addEventListener('click',openCart);el.close?.addEventListener('click',closeCart);el.scrim?.addEventListener('click',closeCart);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCart()});window.addEventListener('vt-store-cart-change',async()=>{updateCartBadge();await renderCart()});el.submit?.addEventListener('click',beginCheckout)}
function renderCategories(){const all=`<button class="chip ${state.category==='all'?'active':''}" data-cat="all">All parts</button>`;el.categoryRail.innerHTML=all+data.categories.map(c=>`<button class="chip ${state.category===c.slug?'active':''}" data-cat="${VT.esc(c.slug)}">${VT.esc(c.name)}</button>`).join('');el.categoryRail.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.cat;const u=new URL(location.href);if(state.category==='all')u.searchParams.delete('category');else u.searchParams.set('category',state.category);u.searchParams.delete('cart');history.replaceState(null,'',u);renderCategories();renderBrands();renderProducts()}))}
function renderBrands(){const source=data.products.filter(p=>state.category==='all'||p.category_slug===state.category||p.type===state.category);const brands=[...new Set(source.map(p=>p.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b));state.brands=new Set([...state.brands].filter(x=>brands.includes(x)));el.brands.innerHTML=brands.map(b=>`<label class="filter-check"><input type="checkbox" value="${VT.esc(b)}" ${state.brands.has(b)?'checked':''}><span>${VT.esc(b)}</span></label>`).join('')||'<span class="muted" style="font-size:10px">No brand filters yet.</span>';el.brands.querySelectorAll('input').forEach(i=>i.addEventListener('change',()=>{i.checked?state.brands.add(i.value):state.brands.delete(i.value);renderProducts()}))}
function filtered(){let items=data.products.filter(p=>state.category==='all'||p.category_slug===state.category||p.type===state.category);if(state.brands.size)items=items.filter(p=>state.brands.has(p.brand));if(state.search){items=items.filter(p=>{const hay=[p.name,p.brand,p.model,p.type,p.short_description,...(p.highlights||[]),JSON.stringify(p.specs||{}),JSON.stringify(p.compatibility||{})].join(' ').toLowerCase();return hay.includes(state.search)})}items=[...items];if(state.sort==='name')items.sort((a,b)=>a.name.localeCompare(b.name));else if(state.sort==='brand')items.sort((a,b)=>a.brand.localeCompare(b.brand)||a.name.localeCompare(b.name));else items.sort((a,b)=>(Number(b.featured)-Number(a.featured))||(Number(b.sort_priority||0)-Number(a.sort_priority||0))||a.name.localeCompare(b.name));return items}
function renderProducts(){const items=filtered();el.count.textContent=`${items.length} component${items.length===1?'':'s'}`;if(!items.length){el.grid.innerHTML='<div class="empty-state"><strong>No matching components</strong>Try another search or clear a filter.</div>';return}el.grid.innerHTML=items.map(card).join('');el.grid.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();const p=productMap.get(b.dataset.add);if(!p||!VT.canAdd(p))return;VT.addToCart(p.id,1);VT.toast(`${p.name} added to your cart.`);VT.analytics('add_to_cart',{currency:p.currency||'ZAR',items:[{item_id:p.id,item_name:p.name,item_brand:p.brand,item_category:p.type}]})}));}
function card(p){const m=VT.mediaFor(p),available=VT.canAdd(p),stock=VT.stockLabel(p);return`<article class="product-card"><a href="product.html?slug=${encodeURIComponent(p.slug)}" aria-label="View ${VT.esc(p.name)}"><div class="product-media"><img src="${VT.esc(m.src)}" alt="${VT.esc(m.actual?p.name:VT.categoryLabel(p.type)+' category visual')}" loading="lazy" decoding="async">${!m.actual?'<span class="visual-note">Category visual</span>':''}<div class="product-badges">${p.featured?'<span class="badge">VoltTech pick</span>':''}${p.is_new?'<span class="badge new">New</span>':''}</div></div></a><div class="product-body"><span class="product-brand">${VT.esc(p.brand)} · ${VT.esc(VT.categoryLabel(p.type))}</span><a href="product.html?slug=${encodeURIComponent(p.slug)}"><h3>${VT.esc(p.name)}</h3></a><p class="product-desc">${VT.esc(p.short_description||'Verified component specifications with VoltTech compatibility guidance.')}</p><div class="highlights">${(p.highlights||[]).slice(0,3).map(x=>`<span>${VT.esc(x)}</span>`).join('')}</div><div class="price-block"><small>${p.retail_price!=null?'Current listed price':'Current price'}</small><strong>${VT.esc(VT.formatPrice(p.retail_price,p.currency))}</strong><div class="stock-line"><i class="stock-dot"></i>${VT.esc(stock)}</div></div><div class="card-actions"><button class="btn primary small" data-add="${VT.esc(p.id)}" type="button" ${available?'':'disabled'}>${available?'Add to cart':'Unavailable'}</button><a class="icon-btn" href="product.html?slug=${encodeURIComponent(p.slug)}" aria-label="View details" style="display:grid;place-items:center">→</a></div></div></article>`}
function openCart(){el.drawer.classList.add('open');el.scrim.classList.add('open');document.body.classList.add('cart-open');el.drawer.focus();VT.analytics('view_cart',{items:VT.readCart().map(i=>({item_id:i.productId,quantity:i.quantity}))})}
function closeCart(){el.drawer.classList.remove('open');el.scrim.classList.remove('open');document.body.classList.remove('cart-open')}
function updateCartBadge(){const n=VT.cartCount();el.cartCount.textContent=n;el.mobileCartCount.textContent=n;el.mobileCart.classList.toggle('has-items',n>0)}
async function renderCart(){const cart=VT.readCart();if(!cart.length){el.cartItems.innerHTML='<div class="empty-state" style="margin-top:20px"><strong>Your cart is empty</strong>Add components from the catalogue. Nothing is charged until VoltTech confirms stock and delivery.</div>';el.submit.disabled=true;return}el.submit.disabled=false;const missing=cart.filter(i=>!productMap.has(i.productId)).map(i=>i.productId);if(missing.length){try{(await VT.getProductsByIds(missing)).forEach(p=>productMap.set(p.id,p))}catch{}}el.cartItems.innerHTML=cart.map(i=>{const p=productMap.get(i.productId);if(!p)return'';const m=VT.mediaFor(p);return`<div class="cart-row"><img class="cart-thumb" src="${VT.esc(m.src)}" alt=""><div class="cart-copy"><b>${VT.esc(p.name)}</b><small>${VT.esc(p.brand)} · ${VT.esc(VT.stockLabel(p))}</small><div class="qty-row"><button type="button" data-dec="${VT.esc(p.id)}" aria-label="Decrease quantity">−</button><span>${i.quantity}</span><button type="button" data-inc="${VT.esc(p.id)}" aria-label="Increase quantity">+</button><button class="remove-link" type="button" data-remove="${VT.esc(p.id)}">Remove</button></div></div></div>`}).join('');el.cartItems.querySelectorAll('[data-dec]').forEach(b=>b.addEventListener('click',()=>VT.setCartQty(b.dataset.dec,(VT.readCart().find(i=>i.productId===b.dataset.dec)?.quantity||1)-1)));el.cartItems.querySelectorAll('[data-inc]').forEach(b=>b.addEventListener('click',()=>VT.setCartQty(b.dataset.inc,(VT.readCart().find(i=>i.productId===b.dataset.inc)?.quantity||0)+1)));el.cartItems.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>VT.setCartQty(b.dataset.remove,0)))}
function beginCheckout(){if(!VT.readCart().length)return;VT.analytics('begin_checkout',{items:VT.readCart().map(i=>({item_id:i.productId,quantity:i.quantity}))});location.href='checkout.html'}
})();
