import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SITE_ORIGIN="https://volttechcomputerco.co.za";
const ALLOWED_ORIGINS=new Set([SITE_ORIGIN,"https://www.volttechcomputerco.co.za","https://volttechcomputerco.github.io"]);
const originAllowed=(origin:string|null)=>!origin||ALLOWED_ORIGINS.has(origin);
const headers=(o:string|null)=>({"Access-Control-Allow-Origin":o&&ALLOWED_ORIGINS.has(o)?o:SITE_ORIGIN,"Access-Control-Allow-Headers":"content-type, apikey, authorization, x-client-info","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Vary":"Origin"});
const reply=(b:unknown,s=200,o:string|null=null)=>new Response(JSON.stringify(b),{status:s,headers:headers(o)});
const clean=(v:unknown,m=200)=>typeof v==="string"?v.trim().slice(0,m):"";
async function sha256Hex(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function clientFingerprint(req:Request){
  const forwarded=(req.headers.get("x-forwarded-for")||"").split(",")[0].trim();
  const ip=forwarded||req.headers.get("x-real-ip")||req.headers.get("cf-connecting-ip")||"unknown";
  const ua=(req.headers.get("user-agent")||"unknown").slice(0,220);
  return ip+"|"+ua;
}
async function rateAllowed(admin:any,bucket:string,key:string,limit:number,windowSeconds:number){
  const keyHash=await sha256Hex(key);
  const {data,error}=await admin.rpc("consume_store_edge_rate_limit",{p_bucket:bucket,p_key_hash:keyHash,p_limit:limit,p_window_seconds:windowSeconds});
  if(error) throw error;
  return data===true;
}

function collectRates(data:any):any[]{if(Array.isArray(data))return data;if(!data||typeof data!=="object")return[];for(const k of ["rates","service_levels","shipping_rates","data","results"]){if(Array.isArray(data[k]))return data[k]}return[]}
function normaliseRate(r:any){const sl=r?.service_level||{};const amount=Number(r?.total_price??r?.rate??r?.price??r?.amount??r?.rate_amount);return{provider_slug:r?.provider_slug||r?.courier_slug||null,courier_name:r?.provider_name||r?.courier_name||r?.courier||null,service_code:r?.service_code||r?.service_level_code||r?.id||sl?.code||null,service_name:r?.service_name||r?.name||sl?.name||r?.service_level_name||null,amount:Number.isFinite(amount)?amount:null,currency:r?.currency||"ZAR",eta:r?.eta||r?.delivery_time||r?.delivery_estimate||sl?.delivery_time||null,pickup_point_location_id:r?.pickup_point_location_id||null,raw:r}}
Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response("ok",{headers:headers(origin)});if(req.method!=="POST")return reply({error:"Method not allowed"},405,origin);if(!originAllowed(origin))return reply({error:"Origin not allowed"},403,origin);
try{const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)return reply({error:"Server configuration error"},500,origin);const admin=createClient(url,service);if(!(await rateAllowed(admin,"shipping_rates_fingerprint",clientFingerprint(req),24,600)))return reply({error:"Too many shipping-rate requests. Please wait a little and try again."},429,origin);const [{data:privateCfg},{data:token}]=await Promise.all([admin.from("store_private_settings").select("value").eq("id","shipping").maybeSingle(),admin.rpc("get_store_secret",{p_name:"bobgo_api_token"})]);const cfg=privateCfg?.value||{};if(!token||!cfg?.configured||!cfg?.collection_address)return reply({configured:false,reason:"Bob Go credentials or private dispatch settings are not configured yet."},200,origin);
const body=await req.json().catch(()=>null),rawItems=Array.isArray(body?.items)?body.items:[],dest=body?.delivery_address||{};if(!rawItems.length)return reply({error:"Cart is empty"},400,origin);const qty=new Map<string,number>();for(const x of rawItems){const id=clean(x?.productId,120),q=Number(x?.quantity);if(!id||!Number.isInteger(q)||q<1||q>25)return reply({error:"Invalid cart item"},400,origin);qty.set(id,(qty.get(id)||0)+q)}const ids=[...qty.keys()];const {data:products,error:pErr}=await admin.from("store_products").select("id,name,retail_price,currency,shipping_weight_kg,shipping_length_cm,shipping_width_cm,shipping_height_cm,shipping_packaging_verified,status,visibility,sale_mode").in("id",ids);if(pErr)throw pErr;if(!products||products.length!==ids.length)return reply({error:"One or more products are unavailable"},409,origin);
const missing=products.filter((p:any)=>!p.shipping_packaging_verified||!p.shipping_weight_kg||!p.shipping_length_cm||!p.shipping_width_cm||!p.shipping_height_cm||p.retail_price==null).map((p:any)=>p.name);if(missing.length)return reply({configured:true,ready:false,reason:"Shipping dimensions or current pricing are still missing for one or more products.",products:missing},200,origin);
const delivery={company:"",street_address:clean(dest.address_line1,160),local_area:clean(dest.suburb||dest.address_line2,120),city:clean(dest.city,120),zone:clean(dest.province,120),country:"ZA",code:clean(dest.postal_code,20)};if(!delivery.street_address||!delivery.city)return reply({error:"Complete the delivery address first"},400,origin);const items=products.map((p:any)=>({description:p.name,price:Number(p.retail_price),quantity:qty.get(p.id)||1,length_cm:Number(p.shipping_length_cm),width_cm:Number(p.shipping_width_cm),height_cm:Number(p.shipping_height_cm),weight_kg:Number(p.shipping_weight_kg)}));const declared=items.reduce((n:number,i:any)=>n+i.price*i.quantity,0);const environment=cfg?.environment==="production"?"production":"sandbox";const base=environment==="production"?"https://api.bobgo.co.za/v2":"https://api.sandbox.bobgo.co.za/v2";const payload={collection_address:cfg.collection_address,delivery_address:delivery,items,declared_value:declared,handling_time:Number(cfg.handling_time_days||1)};const resp=await fetch(`${base}/rates-at-checkout`,{method:"POST",headers:{Authorization:`Bearer ${token}`,Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify(payload)});const text=await resp.text();let data:any=null;try{data=JSON.parse(text)}catch{}if(!resp.ok){console.error("BobGo RAC",resp.status,text);return reply({configured:true,ready:true,error:"Shipping rates are temporarily unavailable"},502,origin)}const rates=collectRates(data).map(normaliseRate).filter((r:any)=>r.amount!=null).sort((a:any,b:any)=>a.amount-b.amount);return reply({configured:true,ready:true,environment,rates,raw_count:collectRates(data).length},200,origin)}catch(e){console.error("bobgo-checkout-rates",e);return reply({error:"Could not load shipping rates"},500,origin)}});