import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const repo = process.cwd();
const outDir = path.join(repo, 'qa-results');
fs.mkdirSync(outDir, { recursive: true });

const tasks = [
  ['Clean frontend source/output contract', 'python3', ['scripts/check-clean-frontend.py']],
  ['Domain residue gate', 'python3', ['scripts/check-domain-residue.py']],
  ['Final SEO gate', 'python3', ['scripts/check-final-seo.py']],
  ['STATIC history migration gate', 'python3', ['scripts/test-static-history-migration.py']],
  ['STATIC publishing validation', 'python3', ['scripts/validate-static.py']],
  ['Repo-wide public HTML/link scan', 'python3', ['scripts/check-full-site.py']],

  ['Runtime + launch flags + mobile shell', 'node', ['scripts/test-clean-runtime.mjs']],
  ['Accessibility + performance contracts', 'node', ['scripts/test-clean-a11y-performance.mjs']],
  ['Account/auth boundary', 'node', ['scripts/test-clean-account.mjs']],
  ['Builder contracts', 'node', ['scripts/test-clean-builder.mjs']],
  ['Commerce catalogue contracts', 'node', ['scripts/test-clean-commerce.mjs']],
  ['Transactions/payment gate', 'node', ['scripts/test-clean-transactions.mjs']],
  ['Creator Hub contracts', 'node', ['scripts/test-clean-creator-hub.mjs']],
  ['Customer operations', 'node', ['scripts/test-clean-customer-ops.mjs']],
  ['Customer records', 'node', ['scripts/test-clean-customer-records.mjs']],
  ['Customer document support', 'node', ['scripts/test-clean-document-support.mjs']],
  ['Printable documents', 'node', ['scripts/test-clean-documents.mjs']],
  ['Canonical/domain source contracts', 'node', ['scripts/test-clean-domain.mjs']],
  ['Legal/support family', 'node', ['scripts/test-clean-legal.mjs']],
  ['Service funnel round trip', 'node', ['scripts/test-clean-service-funnel.mjs']],
  ['Service family contracts', 'node', ['scripts/test-clean-services.mjs']],
  ['Signal Scan contracts', 'node', ['scripts/test-clean-signal-scan.mjs']],
  ['STATIC hub/feed/workflows', 'node', ['scripts/test-clean-static.mjs']],
  ['Streaming/Stream Scan contracts', 'node', ['scripts/test-clean-streaming.mjs']],
];

const startedAt = new Date().toISOString();
const results = [];
let failed = 0;

console.log(`VoltTech Step 9.1 full QA — ${tasks.length} gates`);
console.log('Branch target: clean-rebuild\n');

for (let i = 0; i < tasks.length; i += 1) {
  const [name, command, args] = tasks[i];
  const label = `[${String(i + 1).padStart(2, '0')}/${tasks.length}] ${name}`;
  console.log(`\n=== ${label} ===`);

  const start = Date.now();
  const run = spawnSync(command, args, {
    cwd: repo,
    encoding: 'utf8',
    env: process.env,
    maxBuffer: 16 * 1024 * 1024,
  });

  if (run.stdout) process.stdout.write(run.stdout);
  if (run.stderr) process.stderr.write(run.stderr);

  const status = run.status === 0 ? 'PASS' : 'FAIL';
  if (status === 'FAIL') failed += 1;

  results.push({
    name,
    command: [command, ...args].join(' '),
    status,
    exit_code: run.status,
    duration_ms: Date.now() - start,
    signal: run.signal ?? null,
  });

  console.log(`${status}: ${name}`);
}

const finishedAt = new Date().toISOString();
const summary = {
  step: '9.1',
  title: 'Automated Full Regression QA',
  branch: 'clean-rebuild',
  started_at: startedAt,
  finished_at: finishedAt,
  total: results.length,
  passed: results.length - failed,
  failed,
  status: failed === 0 ? 'PASS' : 'FAIL',
  results,
};

fs.writeFileSync(
  path.join(outDir, 'step-9.1-summary.json'),
  `${JSON.stringify(summary, null, 2)}\n`,
  'utf8',
);

const md = [
  '# VoltTech Step 9.1 — Full QA summary',
  '',
  `Overall: **${summary.status}**`,
  '',
  `Passed: ${summary.passed}/${summary.total}`,
  `Failed: ${summary.failed}/${summary.total}`,
  '',
  '| Gate | Result |',
  '| --- | --- |',
  ...results.map((r) => `| ${r.name.replaceAll('|', '\\|')} | ${r.status} |`),
  '',
  'Generated by `scripts/run-full-qa.mjs`.',
  '',
].join('\n');

fs.writeFileSync(path.join(outDir, 'step-9.1-summary.md'), md, 'utf8');

console.log(`\n=== STEP 9.1 ${summary.status} ===`);
console.log(`${summary.passed}/${summary.total} gates passed.`);
console.log('Evidence written to qa-results/.');

process.exit(failed === 0 ? 0 : 1);

// Step 9.1 correction rerun marker — 2026-09-25.
