import {getClient,canTransactHere} from './session.js';
export {canTransactHere};
export const cartKey='vt_store_quote_cart_v1';
export const publicProducts=rows=>(Array.isArray(rows)?rows:[]).filter(p=>p&&p.status==='active'&&p.visibility==='public'&&p.sale_mode!=='hidden'&&p.is_demo===false);
export const canAdd=p=>publicProducts([p]).length===1&&!['out_of_stock','out-of-stock','discontinued','unavailable'].includes(String(p.stock_status||'').toLowerCase())&&(p.stock_qty==null||Number(p.stock_qty)>0);
export function checkoutCart(raw){if(!Array.isArray(raw)||raw.length>30)return null;const ids=new Set();for(const i of raw){if(!i||typeof i.productId!=='string'||!i.productId.trim()||i.productId.length>120||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>25||ids.has(i.productId))return null;ids.add(i.productId);}return raw.map(i=>({productId:i.productId,quantity:i.quantity}));}
export function readCart(){try{return checkoutCart(JSON.parse(localStorage.getItem(cartKey)||'[]'))||[];}catch{return [];}}
export function saveCart(items){if(!checkoutCart(items))throw Error('Cart limits exceeded.');localStorage.setItem(cartKey,JSON.stringify(items));window.dispatchEvent(new Event('vt-store-cart-change'));}
export function changeQty(id,qty){const cart=readCart();const entry=cart.find(i=>i.productId===id);if(qty<=0){saveCart(cart.filter(i=>i.productId!==id));return;}if(!Number.isInteger(qty)||qty>25)throw Error('Maximum quantity is 25.');if(entry)entry.quantity=qty;else cart.push({productId:id,quantity:qty});saveCart(cart);}
export const fingerprint=items=>JSON.stringify([...items].map(i=>[i.productId,i.quantity]).sort((a,b)=>a[0].localeCompare(b[0])));
export async function query(table,modify=x=>x){const client=await getClient();const result=await modify(client.from(table).select('*'));if(result.error)throw Error(result.error.message);return result.data;}
export async function settings(){return query('store_settings',x=>x.eq('id','store').single());}
export async function catalogue(){const s=await settings();if(!s.catalogue_enabled)return{settings:s,products:[],categories:[],closed:true};const [products,categories]=await Promise.all([query('store_products',x=>x.eq('status','active').eq('visibility','public').neq('sale_mode','hidden').eq('is_demo',false).order('sort_priority',{ascending:false}).order('name')),query('store_categories',x=>x.eq('is_active',true).order('sort_order'))]);return{settings:s,products:publicProducts(products),categories};}
export async function productsById(ids){if(!ids.length)return[];return publicProducts(await query('store_products',x=>x.in('id',ids).eq('status','active').eq('visibility','public').neq('sale_mode','hidden').eq('is_demo',false)));}
export async function productBySlug(slug){const s=await settings();if(!s.catalogue_enabled)return null;const rows=await query('store_products',x=>x.eq('slug',slug).eq('status','active').eq('visibility','public').neq('sale_mode','hidden').eq('is_demo',false));return publicProducts(rows)[0]||null;}
export async function invoke(name,body){if(!canTransactHere())throw Error('This transaction is available only on the live VoltTech domain.');const client=await getClient();const r=await client.functions.invoke(name,{body});if(r.error){const failure=Error(r.error.message);failure.status=Number(r.error.context?.status)||0;failure.uncertain=!failure.status||failure.status>=500;throw failure;}if(r.data?.error)throw Error(r.data.error);return r.data;}
export function validOrderAccess(params){const ref=params.get('ref')||'',token=params.get('token')||'';return ref.length>0&&ref.length<=80&&/^[a-f0-9]{64}$/i.test(token)?{ref,token}:null;}
export function statusDestination(result){try{const raw=result?.status_url||(result?.request?.request_number&&result?.access_token?`order-status.html?ref=${encodeURIComponent(result.request.request_number)}&token=${encodeURIComponent(result.access_token)}`:'');if(!raw)return '';const u=new URL(raw,location.href);return u.origin===location.origin&&u.pathname==='/order-status.html'&&!u.username&&!u.password&&validOrderAccess(u.searchParams)?u.href:'';}catch{return '';}}
export function paymentDestination(raw){try{const u=new URL(raw);return u.protocol==='https:'&&u.hostname==='c.yoco.com'&&!u.username&&!u.password&&(!u.port||u.port==='443')?u.href:'';}catch{return '';}}
export function shippingRate(result){if(result?.configured!==true||result?.ready!==true||result?.environment!=='production'||!Array.isArray(result.rates))return null;return result.rates.filter(r=>r&&r.currency==='ZAR'&&r.amount!==null&&r.amount!==''&&Number.isFinite(Number(r.amount))&&Number(r.amount)>=0).sort((a,b)=>Number(a.amount)-Number(b.amount))[0]||null;}
export function canPay(order,s){return s?.direct_payment_enabled===true&&order?.can_pay===true&&order.checkout_stage==='awaiting_payment'&&!['paid','refunded','partially_refunded','cancelled'].includes(order.payment_status)&&Number.isFinite(Number(order.total))&&Number(order.total)>0;}
export function eligibleCart(cart,products){if(!cart?.length)return false;const map=new Map(publicProducts(products).map(p=>[p.id,p]));return cart.every(i=>{const p=map.get(i.productId);return p&&canAdd(p)&&(p.stock_qty==null||Number(p.stock_qty)>=i.quantity);});}
